//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string BuidingNumber { get; set; }
        public string WarehouseCode { get; set; }
        public string FionameSender { get; set; }
        public string FionzmeRecioient { get; set; }
        public string DeliveryAddress { get; set; }
        public string PostalCode { get; set; }
        public string Phon { get; set; }
        public string Weight { get; set; }
        public string Note { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
